---
version: "3"

services:
  confluence:
    image: "atlassian/confluence-server"
    ports:
      - "8090:8090"
      - "8091:8091"
    volumes:
      - "confluence:/var/atlassian/application-data/confluence:rw"

volumes:
  confluence: